Silently forward error without debug message in compress_data_internal
Resolved a bug that caused an error message
("../lib/icu_compress/cmp_icu.c:2229: Error: forwarding error in bitsize: ...")
to display when DEBUGLEVEL is set to 3. This behavior is
unintended as the compressor is designed to handle such errors by
inserting the uncompressed data directly into the bitstream.
Consequently, the error forwarding process has been made silent.